### ISSUE TITLE
// @endif outputs whatever is behind the @endif token

### ISSUE THREAD

**Issue by doberkofler** [jsoverson/preprocess#103]
When preprocessing the following code without the DEBUG environment variable set:

``` javascript
'use strict';
var pp = require('preprocess');
var text = '//start\n// @ifdef DEBUG\nvar some;\n// @endif DEBUG\n//end';
console.log(pp.preprocess(text, {}, {type: 'js'}));
```

you would imagine, that the `//start` and `//end`lines will be returned but instead the following text will be returned:

```
//start
DEBUG
//end
```

Unfortunately preprocess will output whatever text is behind the `@endif` token and this seems very wrong to me.

**Comment by kajmagnus** [comment]
I break out `\nvar some;\n// ` to a separate variable, and wrap it in `@ifdef` to deal with that.
