### ISSUE TITLE
Pass variables to includes?

### ISSUE THREAD

**Issue by mhulse** [jsoverson/preprocess#30]
There have been times where I'd like to tell an include something based on parent template … Maybe there's a better way that I'm not aware of, but it would be nice to have the ability to pass variables to the preprocessed include files.

For a Grunt example, [grunt-include-replace](https://github.com/alanshaw/grunt-include-replace):

``` html
@@include('/path/to/include/message.html', {"name": "Joe Bloggs"})
```

Would it makes sense for Preprocess to allow for variables, defined at the template level (i.e., at the time of the include call) to be passed to the included files?

**Comment by karneaud** [comment]
Was this ever implemented?
