### ISSUE TITLE
@exclude does not seem to work in javascript files.

### ISSUE THREAD

**Issue by surajreddy** [jsoverson/preprocess#32]
I seem to have trouble with the @exclude parameter in javascript - the preprocessing fails with:

```javascript
// @exclude
var test = 4;
// @endexclude
var test2 = 5;
```

It seems to be getting ignored.

I'm getting this while using the library with gulp-preprocessor, see https://github.com/jas/gulp-preprocess/issues/7

**Comment by BendingBender** [comment]
@surajreddy and @simkessy, can you still reproduce the problem with the latest version? I took the above example but for me everything worked fine.

**Comment by BendingBender** [comment]
Closing this because author don't respond.
