### ISSUE TITLE
Not found prints to file

### ISSUE THREAD

**Issue by M1ke** [jsoverson/preprocess#35]
Just found that when running through `gulp-preprocess` (which I think is just a wrapper) it will print 

    /path/to/file not found

Directly into the concatenated script. Is there intended to be a catchable error here, e.g. that could output to a build tool like [gulp](http://gulpjs.com)? I've altered my version to add /* */ around this error so that at least it doesn't break your script entirely; if you think that's reasonable I'll send a pull request.

**Comment by BendingBender** [comment]
It would be great if the lib would throw an error if a file that has to be included/extended can not be found along with some option on the context to opt in to not throwing an error in such case. This will however impose a breaking change.
