### ISSUE TITLE
add .ts extension, for processing TypeScript files.

### ISSUE THREAD

**Issue by sushicutta** [jsoverson/preprocess#37]
In the file regexrules.js, i'd like to have this inside:

   module.exports.ts         = module.exports.js;

so we can process TypeScript sourcefiles the same way it works for JavaScript sourcefiles.

see image :)

![image](https://cloud.githubusercontent.com/assets/503200/4630900/3aaafd46-53b1-11e4-9138-2885610f5be1.png)

**Comment by BendingBender** [comment]
The typescript support was merged in #24. Closing this.

**Comment by sushicutta** [comment]
Thanks Buddy !
