### ISSUE TITLE
CoffeeScript preprocessing deletes statements

### ISSUE THREAD

**Issue by morungos** [jsoverson/preprocess#39]
There's something fatally awry with the end-termination of CoffeeScript preprocessing. The typical effect is that the statement after a `@if` and after an `@endif` are both omitted, even when there are blank lines between the condition and the statement. The regexes appear wrong -- they look for JS-style comment terminators after the comments, which never exist in CS. But I admit, I haven't yet worked through a precise identification of where the patterns are broken. My test issue is:

```
    ## @if NODE_ENV == 'development'
    host = 'localhost'
    protocol = 'http'
    port = 3001
    ## @endif

    console.log "Socket info", protocol, host, port
```

After preprocessing, both the `console.log` and the `host` assignment are both omitted.

**Comment by elado** [comment]
I actually couldn't make it work properly on CoffeeScript:


```coffeescript
# @ifdef FLAG
alert "flag"
# @endif

## @ifdef FLAG
alert "flag"
## @endif

## @ifndef FLAG
alert "no-flag"
## @endif

## @ifdef FLAG *
alert "flag"
## @endif *

## @ifndef FLAG *
alert "no-flag"
## @endif *
```

All alerts are showing in the source.


Only way I've found is wrapping conditions with strings (ew, I know):

```coffeescript
"/* @ifdef FLAG */"
alert "flag"
"/* @endif */"
```

**Comment by elado** [comment]
Duh. I was executing gulp coffee before preprocess. Switched the order.

This worked, and apparently the extra `*` @morungos suggested is needed in some cases.

```coffeescript
# @ifdef FLAG *
alert "flag"
# @endif *

# @ifndef FLAG *
alert "no-flag"
# @endif *
```

**Comment by BendingBender** [comment]
@morungos and @elado could you please verify that the issue no longer appears with current master?
