### ISSUE TITLE
@exec seems to not support multiple params correctly?

### ISSUE THREAD

**Issue by alias1** [jsoverson/preprocess#54]
I'm not 100% if this is a true bug or me breaking something, but when I try and use `@exec` it crams all of the parameters into `arguments[0]`

Looking at the `preprocess/test/preprocess_test.js` tests, it looks as though they wouldn't pick this up as they split then join the array anyway.

`function multiParams() { return arguments.length; }`

`/* @exec multiParams("one", "two", "three") */`

Expect: 3
Actual: 1

Hacky workaround
`function multiParams() { String(arguments[0]).split(',').length; }`

Yet it seems my workaround breaks the ability to call with other env vars as params

`'/* @exec valueOrDefault(FOO_PORT, '8080') */'` -> `'FOO_PORT',`

**Comment by BendingBender** [comment]
@alias1 could you please test current master with your setup? Your problem should be fixed now.
