### ISSUE TITLE
Question: What is the static_path function, and where/how is it defined?

### ISSUE THREAD

**Issue by jonesnc** [jsoverson/preprocess#57]
In the README, a function called `static_path` is called like this:

`<script src="<!-- @exec static_path('another/production/javascript.js') -->"></script>`

Could you provide some more information on what this function does and how it's defined?

**Comment by BendingBender** [comment]
When you execute the the preprocess function, you give it a context. This context is an object containing your variables and it may contain functions. So in the example above a function named `static_path` is called that was passed via the context object.
You can see an example of this happening in test/preprocess_test.js, line 579. Here a function named `hello` is passed via context object.

**Comment by jonesnc** [comment]
>Can I close the issue?

Yes. 

Thanks for enlightening me.
