### ISSUE TITLE
Publish v2.3.1 to npm

### ISSUE THREAD

**Issue by BendingBender** [jsoverson/preprocess#60]
@jsoverson could you please publish v2.3.1 (already tagged) and optionally also 2.3.0 to npm?

Thanks!

**Comment by BendingBender** [comment]
@jsoverson any possibility to get commit access to jsoverson/grunt-preprocess and npm publish rights for preprocess and grnut-preprocess?

**Comment by jsoverson** [comment]
Yep, definitely. `bendingbender` on npm also?

**Comment by BendingBender** [comment]
Yes.

**Comment by jsoverson** [comment]
Added bendingbender as an author and published 2.3.1. Thanks for the work, make sure to add credit to the readme!
