### ISSUE TITLE
html/js regex might not work with mac/windows eol

### ISSUE THREAD

**Issue by syndr0m** [jsoverson/preprocess#8]
Example:
```javascript
 // @ifdef DEBUG
 someDebuggingCall()
 // @endif
```
is using regex "(?://|/\\*)[ \t]*@ifdef[ \t]*([^\n*]*)[ \t]*(?:\\*/)?" which assume eol is "\n"

if your end of line is "\r\n", then "DEBUG\r" is searched in context instead of "DEBUG"

until fixed, a quick workaround is to use the /* */ syntax:
```javascript
 /*@ifdef DEBUG*/
 (...)
 /*@endif*/
```

**Comment by BendingBender** [comment]
Any updates on this?
