### ISSUE TITLE
Asking for advace: if()s

### ISSUE THREAD

**Issue by IngwiePhoenix** [jsoverson/preprocess#80]
I was originally working on my own preprocessor, but found myself beign stuck at the if-statements `#ifdef`, `#ifndef`, `#elif`, `#else` and `#endif`. So I was looking to see if maybe I could get some advice?

My current code is here: https://gist.github.com/IngwiePhoenix/26652d80a2dd603e32ce

I am only stuck on the processing of if statements. Any advice would be really nice!

The preprocessor is ment to become a middleware for a project of mine, which runs middlewares before and after the [oj](https://github.com/musictheory/oj) compiler is run.

Kind regards, Ingwie.

**Comment by BendingBender** [comment]
You could try out [node-ssi](https://npmjs.org/package/ssi) which offers the features you need.
