### ISSUE TITLE
@include as string

### ISSUE THREAD

**Issue by Mottie** [jsoverson/preprocess#93]
In my build process, I compile sass and I would like to inject it into the page (I'm working on a bookmarklet). When using the following format, preprocess leaves the `@include` untouched.

```js
var el = document.createElement( 'style' );
document.querySelector( 'head' ).appendChild( el );
el.innerHTML = '@include-static src/compiled-from-sass.css';
```

I'll switch to use a replace method for now, unless there is a correct method of which I am unaware?

**Comment by Frizi** [comment]
use this instead
```javascript
el.innerHTML = '/* @include-static src/compiled-from-sass.css */';
```

preprocess is just a set of semi-dumb regex replaces, it doesn't care about strings ;) A comment-like string is just as good as a real comment for it.

**Comment by Mottie** [comment]
Oh that's great thanks!
